using System.Text.Json;

namespace RouteGuard.Platform.TripExecutionMonitoring.Domain.Model.Commands;

/// <summary>
/// Command to synchronize a batch of offline events generated by the mobile app.
/// </summary>
public record SyncOfflineRecordsCommand(
    Guid TripId,
    int RecordsCount,
    JsonElement RawPayload
);