spring.application.name=routeguard
spring.profiles.active=dev

# Naming strategy
spring.jpa.hibernate.naming.physical-strategy=com.routegolem.routeguard.shared.infrastructure.persistence.jpa.strategy.SnakeCaseWithPluralizedTablePhysicalNamingStrategy
