# Development profile
spring.datasource.url=jdbc:postgresql://localhost:5432/routeguard_db
spring.datasource.username=postgres
spring.datasource.password=archaludon
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect

# Developer-friendly JPA behavior
spring.jpa.show-sql=true
spring.jpa.hibernate.ddl-auto=update
spring.jpa.open-in-view=true

# App port
server.port=${PORT:8080}