# Spring Application Name
spring.application.name=RouteGuard Platform

# Default to development when no explicit profile is provided.
spring.profiles.default=dev

# Shared Spring DataSource Configuration (PostgreSQL)
spring.datasource.driver-class-name=org.postgresql.Driver

# Shared Spring Data JPA Hibernate Configuration (Adaptado a tu paquete)
spring.jpa.hibernate.naming.physical-strategy=com.routegolem.routeguard.shared.infrastructure.persistence.jpa.configuration.strategy.SnakeCaseWithPluralizedTablePhysicalNamingStrategy

# Application Information for Documentation (Sin arrobas para evitar el crash)
documentation.application.description=RouteGuard School Bus Tracking API
documentation.application.version=1.0.0

# JWT Configuration Properties
authorization.jwt.secret=RouteGuardSuperSecretStringForTokenSigningCredentials2026
authorization.jwt.expiration.days=7

# i18n message bundles
spring.messages.basename=messages
spring.messages.encoding=UTF-8

# Flyway Configuration
spring.flyway.enabled=false