package com.routegolem.routeguard.tracking.infrastructure.persistence.jpa.assemblers;

import com.routegolem.routeguard.tracking.domain.model.aggregates.VehicleLocation;
import com.routegolem.routeguard.tracking.domain.model.valueobjects.Coordinates;
import com.routegolem.routeguard.tracking.infrastructure.persistence.jpa.entities.VehicleLocationPersistenceEntity;

public final class VehicleLocationPersistenceAssembler {

    private VehicleLocationPersistenceAssembler() {}

    // Translates DB to Domain
    public static VehicleLocation toDomainFromPersistence(VehicleLocationPersistenceEntity entity){
        if (entity == null) return null;

        Coordinates coordinates = new Coordinates(entity.getLatitude(), entity.getLongitude());
        return new VehicleLocation(entity.getVehicleId(), coordinates);
    }

    public static VehicleLocationPersistenceEntity toPersistenceFromDomain(VehicleLocation domain){
        if (domain == null) return null;

        VehicleLocationPersistenceEntity entity = new VehicleLocationPersistenceEntity();

        // The JPA entity's id is autogenerated in the DB or is mapped if is getting updated
        entity.setVehicleId(domain.getVehicleId());
        entity.setLatitude(domain.getCurrentCoordinates().latitude());
        entity.setLongitude(domain.getCurrentCoordinates().longitude());
        entity.setLastUpdatedAt(domain.getLastUpdatedAt());

        return entity;
    }
}
