// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using RouteGuard.Platform.Shared.Infrastructure.Persistence.EntityFrameworkCore.Configuration;

#nullable disable

namespace RouteGuard.Platform.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260703211929_AddIamBoundedContext")]
    partial class AddIamBoundedContext
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("RouteGuard.Platform.Fleet.Domain.Model.Aggregates.Route", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("char(36)")
                        .HasColumnName("id");

                    b.Property<string>("DepartureTime")
                        .HasColumnType("longtext")
                        .HasColumnName("departure_time");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("varchar(120)")
                        .HasColumnName("name");

                    b.Property<Guid>("OrganizationId")
                        .HasColumnType("char(36)")
                        .HasColumnName("organization_id");

                    b.Property<string>("ServiceDays")
                        .HasColumnType("longtext")
                        .HasColumnName("service_days");

                    b.Property<string>("State")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("state");

                    b.HasKey("Id")
                        .HasName("p_k_routes");

                    b.ToTable("routes");
                });

            modelBuilder.Entity("RouteGuard.Platform.Iam.Domain.Model.Aggregates.Organization", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("char(36)")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset?>("CreatedAt")
                        .HasColumnType("datetime")
                        .HasColumnName("created_at");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("varchar(150)")
                        .HasColumnName("name");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)")
                        .HasColumnName("status");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasColumnType("datetime")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("p_k_organizations");

                    b.ToTable("organizations", (string)null);
                });

            modelBuilder.Entity("RouteGuard.Platform.Iam.Domain.Model.Aggregates.User", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("char(36)")
                        .HasColumnName("id");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("email");

                    b.Property<Guid?>("OrganizationId")
                        .HasColumnType("char(36)")
                        .HasColumnName("organization_id");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("password_hash");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)")
                        .HasColumnName("role");

                    b.HasKey("Id")
                        .HasName("p_k_users");

                    b.HasIndex("Email")
                        .IsUnique()
                        .HasDatabaseName("i_x_users_email");

                    b.ToTable("users", (string)null);
                });

            modelBuilder.Entity("RouteGuard.Platform.Notifications.Domain.Model.Aggregates.Notification", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("char(36)")
                        .HasColumnName("id");

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("category");

                    b.Property<string>("DeliveryState")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)")
                        .HasColumnName("delivery_state");

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("varchar(1000)")
                        .HasColumnName("message");

                    b.Property<Guid>("OrganizationId")
                        .HasColumnType("char(36)")
                        .HasColumnName("organization_id");

                    b.Property<Guid>("ParentId")
                        .HasColumnType("char(36)")
                        .HasColumnName("parent_id");

                    b.Property<DateTimeOffset>("SentAt")
                        .HasColumnType("datetime")
                        .HasColumnName("sent_at");

                    b.Property<Guid>("TripId")
                        .HasColumnType("char(36)")
                        .HasColumnName("trip_id");

                    b.HasKey("Id")
                        .HasName("p_k_notifications");

                    b.ToTable("notifications", (string)null);
                });

            modelBuilder.Entity("RouteGuard.Platform.Stakeholder.Domain.Model.Aggregates.Parent", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("char(36)")
                        .HasColumnName("id");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("email");

                    b.Property<Guid>("OrganizationId")
                        .HasColumnType("char(36)")
                        .HasColumnName("organization_id");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)")
                        .HasColumnName("phone_number");

                    b.Property<Guid>("UserId")
                        .HasColumnType("char(36)")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("p_k_parents");

                    b.ToTable("parents", (string)null);
                });

            modelBuilder.Entity("RouteGuard.Platform.Stakeholder.Domain.Model.Entities.Driver", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("char(36)")
                        .HasColumnName("id");

                    b.Property<bool>("Available")
                        .HasColumnType("tinyint(1)")
                        .HasColumnName("available");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("email");

                    b.Property<string>("LicenseNumber")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("license_number");

                    b.Property<Guid>("OrganizationId")
                        .HasColumnType("char(36)")
                        .HasColumnName("organization_id");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)")
                        .HasColumnName("phone_number");

                    b.Property<Guid>("UserId")
                        .HasColumnType("char(36)")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("p_k_drivers");

                    b.ToTable("drivers", (string)null);
                });

            modelBuilder.Entity("RouteGuard.Platform.Stakeholder.Domain.Model.Entities.StudentGroup", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("char(36)")
                        .HasColumnName("id");

                    b.Property<string>("ChildIds")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("child_ids");

                    b.Property<bool>("IsFinalizedValue")
                        .HasColumnType("tinyint(1)")
                        .HasColumnName("is_finalized_value");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("name");

                    b.Property<Guid>("OrganizationId")
                        .HasColumnType("char(36)")
                        .HasColumnName("organization_id");

                    b.HasKey("Id")
                        .HasName("p_k_student_groups");

                    b.ToTable("student_groups", (string)null);
                });

            modelBuilder.Entity("RouteGuard.Platform.Subscription.Domain.Model.Aggregates.Plan", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("char(36)")
                        .HasColumnName("id");

                    b.Property<int>("DriverQuota")
                        .HasColumnType("int")
                        .HasColumnName("driver_quota");

                    b.Property<decimal>("Price")
                        .HasPrecision(10, 2)
                        .HasColumnType("decimal(10,2)")
                        .HasColumnName("price");

                    b.Property<int>("RouteQuota")
                        .HasColumnType("int")
                        .HasColumnName("route_quota");

                    b.Property<string>("Tier")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)")
                        .HasColumnName("tier");

                    b.HasKey("Id")
                        .HasName("p_k_plans");

                    b.ToTable("plans", (string)null);
                });

            modelBuilder.Entity("RouteGuard.Platform.Subscription.Domain.Model.Aggregates.Subscription", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("char(36)")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("EndDate")
                        .HasColumnType("datetime")
                        .HasColumnName("end_date");

                    b.Property<Guid>("OrganizationId")
                        .HasColumnType("char(36)")
                        .HasColumnName("organization_id");

                    b.Property<Guid>("PlanId")
                        .HasColumnType("char(36)")
                        .HasColumnName("plan_id");

                    b.Property<DateTimeOffset>("StartDate")
                        .HasColumnType("datetime")
                        .HasColumnName("start_date");

                    b.Property<string>("State")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)")
                        .HasColumnName("state");

                    b.HasKey("Id")
                        .HasName("p_k_subscriptions");

                    b.HasIndex("PlanId")
                        .HasDatabaseName("i_x_subscriptions_plan_id");

                    b.ToTable("subscriptions", (string)null);
                });

            modelBuilder.Entity("RouteGuard.Platform.Trip.Domain.Model.Aggregates.Trip", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("char(36)")
                        .HasColumnName("id");

                    b.Property<Guid>("DriverId")
                        .HasColumnType("char(36)")
                        .HasColumnName("driver_id");

                    b.Property<DateTimeOffset?>("EndTime")
                        .HasColumnType("datetime")
                        .HasColumnName("end_time");

                    b.Property<Guid>("OrganizationId")
                        .HasColumnType("char(36)")
                        .HasColumnName("organization_id");

                    b.Property<Guid>("RouteId")
                        .HasColumnType("char(36)")
                        .HasColumnName("route_id");

                    b.Property<DateTimeOffset?>("StartTime")
                        .HasColumnType("datetime")
                        .HasColumnName("start_time");

                    b.Property<string>("State")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("state");

                    b.HasKey("Id")
                        .HasName("p_k_trips");

                    b.HasIndex("RouteId")
                        .HasDatabaseName("i_x_trips_route_id");

                    b.ToTable("trips");
                });

            modelBuilder.Entity("RouteGuard.Platform.Fleet.Domain.Model.Aggregates.Route", b =>
                {
                    b.OwnsOne("RouteGuard.Platform.Fleet.Domain.Model.Entities.Assignment", "Assignment", b1 =>
                        {
                            b1.Property<Guid>("Id")
                                .HasColumnType("char(36)")
                                .HasColumnName("id");

                            b1.Property<string>("ChildIds")
                                .IsRequired()
                                .HasColumnType("longtext")
                                .HasColumnName("child_ids");

                            b1.Property<Guid>("DriverId")
                                .HasColumnType("char(36)")
                                .HasColumnName("driver_id");

                            b1.Property<Guid>("RouteId")
                                .HasColumnType("char(36)")
                                .HasColumnName("route_id");

                            b1.HasKey("Id")
                                .HasName("p_k_route_assignments");

                            b1.HasIndex("RouteId")
                                .IsUnique()
                                .HasDatabaseName("i_x_route_assignments_route_id");

                            b1.ToTable("route_assignments", (string)null);

                            b1.WithOwner()
                                .HasForeignKey("RouteId")
                                .HasConstraintName("f_k_route_assignments_routes_route_id");
                        });

                    b.OwnsMany("RouteGuard.Platform.Fleet.Domain.Model.Entities.Stop", "Stops", b1 =>
                        {
                            b1.Property<Guid>("Id")
                                .HasColumnType("char(36)")
                                .HasColumnName("id");

                            b1.Property<string>("Name")
                                .IsRequired()
                                .HasMaxLength(120)
                                .HasColumnType("varchar(120)")
                                .HasColumnName("name");

                            b1.Property<int>("Order")
                                .HasColumnType("int")
                                .HasColumnName("order");

                            b1.Property<Guid>("RouteId")
                                .HasColumnType("char(36)")
                                .HasColumnName("route_id");

                            b1.HasKey("Id")
                                .HasName("p_k_route_stops");

                            b1.HasIndex("RouteId")
                                .HasDatabaseName("i_x_route_stops_route_id");

                            b1.ToTable("route_stops", (string)null);

                            b1.WithOwner()
                                .HasForeignKey("RouteId")
                                .HasConstraintName("f_k_route_stops_routes_route_id");

                            b1.OwnsOne("RouteGuard.Platform.Shared.Domain.Model.ValueObjects.Coordinates", "Coordinates", b2 =>
                                {
                                    b2.Property<Guid>("Id")
                                        .HasColumnType("char(36)")
                                        .HasColumnName("id");

                                    b2.Property<double>("Latitude")
                                        .HasColumnType("double")
                                        .HasColumnName("latitude");

                                    b2.Property<double>("Longitude")
                                        .HasColumnType("double")
                                        .HasColumnName("longitude");

                                    b2.HasKey("Id")
                                        .HasName("p_k_route_stops");

                                    b2.ToTable("route_stops");

                                    b2.WithOwner()
                                        .HasForeignKey("Id")
                                        .HasConstraintName("f_k_route_stops_route_stops_id");
                                });

                            b1.Navigation("Coordinates")
                                .IsRequired();
                        });

                    b.OwnsOne("RouteGuard.Platform.Fleet.Domain.Model.Entities.Vehicle", "Vehicle", b1 =>
                        {
                            b1.Property<Guid>("Id")
                                .HasColumnType("char(36)")
                                .HasColumnName("id");

                            b1.Property<string>("Brand")
                                .IsRequired()
                                .HasMaxLength(80)
                                .HasColumnType("varchar(80)")
                                .HasColumnName("brand");

                            b1.Property<int>("Capacity")
                                .HasColumnType("int")
                                .HasColumnName("capacity");

                            b1.Property<string>("Model")
                                .IsRequired()
                                .HasMaxLength(80)
                                .HasColumnType("varchar(80)")
                                .HasColumnName("model");

                            b1.Property<Guid>("OrganizationId")
                                .HasColumnType("char(36)")
                                .HasColumnName("organization_id");

                            b1.Property<string>("Plate")
                                .IsRequired()
                                .HasMaxLength(20)
                                .HasColumnType("varchar(20)")
                                .HasColumnName("plate");

                            b1.Property<Guid>("RouteId")
                                .HasColumnType("char(36)")
                                .HasColumnName("route_id");

                            b1.HasKey("Id")
                                .HasName("p_k_route_vehicles");

                            b1.HasIndex("RouteId")
                                .IsUnique()
                                .HasDatabaseName("i_x_route_vehicles_route_id");

                            b1.ToTable("route_vehicles", (string)null);

                            b1.WithOwner()
                                .HasForeignKey("RouteId")
                                .HasConstraintName("f_k_route_vehicles_routes_route_id");
                        });

                    b.Navigation("Assignment");

                    b.Navigation("Stops");

                    b.Navigation("Vehicle");
                });

            modelBuilder.Entity("RouteGuard.Platform.Iam.Domain.Model.Aggregates.User", b =>
                {
                    b.OwnsOne("RouteGuard.Platform.Shared.Domain.Model.ValueObjects.FullName", "FullName", b1 =>
                        {
                            b1.Property<Guid>("Id")
                                .HasColumnType("char(36)")
                                .HasColumnName("id");

                            b1.Property<string>("FirstName")
                                .IsRequired()
                                .HasMaxLength(100)
                                .HasColumnType("varchar(100)")
                                .HasColumnName("first_name");

                            b1.Property<string>("LastName")
                                .IsRequired()
                                .HasMaxLength(100)
                                .HasColumnType("varchar(100)")
                                .HasColumnName("last_name");

                            b1.HasKey("Id")
                                .HasName("p_k_users");

                            b1.ToTable("users");

                            b1.WithOwner()
                                .HasForeignKey("Id")
                                .HasConstraintName("f_k_users_users_id");
                        });

                    b.Navigation("FullName")
                        .IsRequired();
                });

            modelBuilder.Entity("RouteGuard.Platform.Notifications.Domain.Model.Aggregates.Notification", b =>
                {
                    b.OwnsMany("RouteGuard.Platform.Notifications.Domain.Model.Entities.Alert", "Alerts", b1 =>
                        {
                            b1.Property<Guid>("Id")
                                .HasColumnType("char(36)")
                                .HasColumnName("id");

                            b1.Property<Guid>("NotificationId")
                                .HasColumnType("char(36)")
                                .HasColumnName("notification_id");

                            b1.Property<Guid>("OwnerNotificationId")
                                .HasColumnType("char(36)")
                                .HasColumnName("owner_notification_id");

                            b1.Property<bool>("Panic")
                                .HasColumnType("tinyint(1)")
                                .HasColumnName("panic");

                            b1.Property<DateTimeOffset>("TriggeredAt")
                                .HasColumnType("datetime")
                                .HasColumnName("triggered_at");

                            b1.HasKey("Id")
                                .HasName("p_k_alerts");

                            b1.HasIndex("OwnerNotificationId")
                                .HasDatabaseName("i_x_alerts_owner_notification_id");

                            b1.ToTable("alerts");

                            b1.WithOwner()
                                .HasForeignKey("OwnerNotificationId")
                                .HasConstraintName("f_k_alerts_notifications_owner_notification_id");
                        });

                    b.OwnsMany("RouteGuard.Platform.Notifications.Domain.Model.Entities.Announcement", "Announcements", b1 =>
                        {
                            b1.Property<Guid>("Id")
                                .HasColumnType("char(36)")
                                .HasColumnName("id");

                            b1.Property<string>("Message")
                                .IsRequired()
                                .HasMaxLength(1000)
                                .HasColumnType("varchar(1000)")
                                .HasColumnName("message");

                            b1.Property<Guid>("NotificationId")
                                .HasColumnType("char(36)")
                                .HasColumnName("notification_id");

                            b1.Property<Guid>("OwnerNotificationId")
                                .HasColumnType("char(36)")
                                .HasColumnName("owner_notification_id");

                            b1.Property<DateTimeOffset>("PublishedAt")
                                .HasColumnType("datetime")
                                .HasColumnName("published_at");

                            b1.Property<Guid>("RouteId")
                                .HasColumnType("char(36)")
                                .HasColumnName("route_id");

                            b1.HasKey("Id")
                                .HasName("p_k_announcements");

                            b1.HasIndex("OwnerNotificationId")
                                .HasDatabaseName("i_x_announcements_owner_notification_id");

                            b1.ToTable("announcements");

                            b1.WithOwner()
                                .HasForeignKey("OwnerNotificationId")
                                .HasConstraintName("f_k_announcements_notifications_owner_notification_id");
                        });

                    b.Navigation("Alerts");

                    b.Navigation("Announcements");
                });

            modelBuilder.Entity("RouteGuard.Platform.Stakeholder.Domain.Model.Aggregates.Parent", b =>
                {
                    b.OwnsOne("RouteGuard.Platform.Shared.Domain.Model.ValueObjects.FullName", "FullName", b1 =>
                        {
                            b1.Property<Guid>("Id")
                                .HasColumnType("char(36)")
                                .HasColumnName("id");

                            b1.Property<string>("FirstName")
                                .IsRequired()
                                .HasMaxLength(100)
                                .HasColumnType("varchar(100)")
                                .HasColumnName("first_name");

                            b1.Property<string>("LastName")
                                .IsRequired()
                                .HasMaxLength(100)
                                .HasColumnType("varchar(100)")
                                .HasColumnName("last_name");

                            b1.HasKey("Id")
                                .HasName("p_k_parents");

                            b1.ToTable("parents");

                            b1.WithOwner()
                                .HasForeignKey("Id")
                                .HasConstraintName("f_k_parents_parents_id");
                        });

                    b.OwnsMany("RouteGuard.Platform.Stakeholder.Domain.Model.Entities.Child", "Children", b1 =>
                        {
                            b1.Property<Guid>("Id")
                                .HasColumnType("char(36)")
                                .HasColumnName("id");

                            b1.Property<int>("Age")
                                .HasColumnType("int")
                                .HasColumnName("age");

                            b1.Property<string>("EnrollmentState")
                                .IsRequired()
                                .HasMaxLength(20)
                                .HasColumnType("varchar(20)")
                                .HasColumnName("enrollment_state");

                            b1.Property<Guid>("ParentId")
                                .HasColumnType("char(36)")
                                .HasColumnName("parent_id");

                            b1.HasKey("Id")
                                .HasName("p_k_children");

                            b1.HasIndex("ParentId")
                                .HasDatabaseName("i_x_children_parent_id");

                            b1.ToTable("children");

                            b1.WithOwner()
                                .HasForeignKey("ParentId")
                                .HasConstraintName("f_k_children_parents_parent_id");

                            b1.OwnsOne("RouteGuard.Platform.Shared.Domain.Model.ValueObjects.FullName", "FullName", b2 =>
                                {
                                    b2.Property<Guid>("Id")
                                        .HasColumnType("char(36)")
                                        .HasColumnName("id");

                                    b2.Property<string>("FirstName")
                                        .IsRequired()
                                        .HasMaxLength(100)
                                        .HasColumnType("varchar(100)")
                                        .HasColumnName("first_name");

                                    b2.Property<string>("LastName")
                                        .IsRequired()
                                        .HasMaxLength(100)
                                        .HasColumnType("varchar(100)")
                                        .HasColumnName("last_name");

                                    b2.HasKey("Id")
                                        .HasName("p_k_children");

                                    b2.ToTable("children");

                                    b2.WithOwner()
                                        .HasForeignKey("Id")
                                        .HasConstraintName("f_k_children_children_id");
                                });

                            b1.Navigation("FullName")
                                .IsRequired();
                        });

                    b.Navigation("Children");

                    b.Navigation("FullName")
                        .IsRequired();
                });

            modelBuilder.Entity("RouteGuard.Platform.Stakeholder.Domain.Model.Entities.Driver", b =>
                {
                    b.OwnsOne("RouteGuard.Platform.Shared.Domain.Model.ValueObjects.FullName", "FullName", b1 =>
                        {
                            b1.Property<Guid>("Id")
                                .HasColumnType("char(36)")
                                .HasColumnName("id");

                            b1.Property<string>("FirstName")
                                .IsRequired()
                                .HasMaxLength(100)
                                .HasColumnType("varchar(100)")
                                .HasColumnName("first_name");

                            b1.Property<string>("LastName")
                                .IsRequired()
                                .HasMaxLength(100)
                                .HasColumnType("varchar(100)")
                                .HasColumnName("last_name");

                            b1.HasKey("Id")
                                .HasName("p_k_drivers");

                            b1.ToTable("drivers");

                            b1.WithOwner()
                                .HasForeignKey("Id")
                                .HasConstraintName("f_k_drivers_drivers_id");
                        });

                    b.Navigation("FullName")
                        .IsRequired();
                });

            modelBuilder.Entity("RouteGuard.Platform.Subscription.Domain.Model.Aggregates.Subscription", b =>
                {
                    b.HasOne("RouteGuard.Platform.Subscription.Domain.Model.Aggregates.Plan", null)
                        .WithMany()
                        .HasForeignKey("PlanId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("f_k_subscriptions_plans_plan_id");
                });

            modelBuilder.Entity("RouteGuard.Platform.Trip.Domain.Model.Aggregates.Trip", b =>
                {
                    b.HasOne("RouteGuard.Platform.Fleet.Domain.Model.Aggregates.Route", null)
                        .WithMany()
                        .HasForeignKey("RouteId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("f_k_trips_routes_route_id");

                    b.OwnsMany("RouteGuard.Platform.Trip.Domain.Model.Entities.Attendance", "Attendances", b1 =>
                        {
                            b1.Property<Guid>("Id")
                                .HasColumnType("char(36)")
                                .HasColumnName("id");

                            b1.Property<DateTimeOffset?>("BoardedAt")
                                .HasColumnType("datetime")
                                .HasColumnName("boarded_at");

                            b1.Property<string>("BoardingState")
                                .IsRequired()
                                .HasColumnType("longtext")
                                .HasColumnName("boarding_state");

                            b1.Property<Guid>("ChildId")
                                .HasColumnType("char(36)")
                                .HasColumnName("child_id");

                            b1.Property<Guid>("TripId")
                                .HasColumnType("char(36)")
                                .HasColumnName("trip_id");

                            b1.HasKey("Id")
                                .HasName("p_k_attendances");

                            b1.HasIndex("TripId")
                                .HasDatabaseName("i_x_attendances_trip_id");

                            b1.ToTable("attendances");

                            b1.WithOwner()
                                .HasForeignKey("TripId")
                                .HasConstraintName("f_k_attendances_trips_trip_id");
                        });

                    b.OwnsMany("RouteGuard.Platform.Trip.Domain.Model.Entities.Incident", "Incidents", b1 =>
                        {
                            b1.Property<Guid>("Id")
                                .HasColumnType("char(36)")
                                .HasColumnName("id");

                            b1.Property<string>("Description")
                                .IsRequired()
                                .HasMaxLength(500)
                                .HasColumnType("varchar(500)")
                                .HasColumnName("description");

                            b1.Property<DateTimeOffset>("ReportedAt")
                                .HasColumnType("datetime")
                                .HasColumnName("reported_at");

                            b1.Property<Guid>("TripId")
                                .HasColumnType("char(36)")
                                .HasColumnName("trip_id");

                            b1.HasKey("Id")
                                .HasName("p_k_incidents");

                            b1.HasIndex("TripId")
                                .HasDatabaseName("i_x_incidents_trip_id");

                            b1.ToTable("incidents");

                            b1.WithOwner()
                                .HasForeignKey("TripId")
                                .HasConstraintName("f_k_incidents_trips_trip_id");
                        });

                    b.Navigation("Attendances");

                    b.Navigation("Incidents");
                });
#pragma warning restore 612, 618
        }
    }
}
