// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using RouteGuard.Platform.Shared.Infrastructure.Persistence.EntityFrameworkCore.Configuration;

#nullable disable

namespace RouteGuard.Platform.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260620214846_InitialCreateSubscriptionContext")]
    partial class InitialCreateSubscriptionContext
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("RouteGuard.Platform.TripExecutionMonitoring.Domain.Model.Aggregates.Trip", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("char(36)")
                        .HasColumnName("id");

                    b.Property<Guid>("DriverId")
                        .HasColumnType("char(36)")
                        .HasColumnName("driver_id");

                    b.Property<DateTimeOffset?>("EndTime")
                        .HasColumnType("datetime")
                        .HasColumnName("end_time");

                    b.Property<Guid>("OrganizationId")
                        .HasColumnType("char(36)")
                        .HasColumnName("organization_id");

                    b.Property<Guid>("RouteId")
                        .HasColumnType("char(36)")
                        .HasColumnName("route_id");

                    b.Property<DateTimeOffset?>("StartTime")
                        .HasColumnType("datetime")
                        .HasColumnName("start_time");

                    b.Property<string>("State")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("state");

                    b.HasKey("Id")
                        .HasName("p_k_trips");

                    b.ToTable("trips");
                });

            modelBuilder.Entity("RouteGuard.Platform.TripExecutionMonitoring.Domain.Model.Aggregates.Trip", b =>
                {
                    b.OwnsMany("RouteGuard.Platform.TripExecutionMonitoring.Domain.Model.Entities.Attendance", "Attendances", b1 =>
                        {
                            b1.Property<Guid>("Id")
                                .HasColumnType("char(36)")
                                .HasColumnName("id");

                            b1.Property<DateTimeOffset?>("BoardedAt")
                                .HasColumnType("datetime")
                                .HasColumnName("boarded_at");

                            b1.Property<string>("BoardingState")
                                .IsRequired()
                                .HasColumnType("longtext")
                                .HasColumnName("boarding_state");

                            b1.Property<Guid>("ChildId")
                                .HasColumnType("char(36)")
                                .HasColumnName("child_id");

                            b1.Property<Guid>("TripId")
                                .HasColumnType("char(36)")
                                .HasColumnName("trip_id");

                            b1.HasKey("Id")
                                .HasName("p_k_attendances");

                            b1.HasIndex("TripId")
                                .HasDatabaseName("i_x_attendances_trip_id");

                            b1.ToTable("attendances");

                            b1.WithOwner()
                                .HasForeignKey("TripId")
                                .HasConstraintName("f_k_attendances_trips_trip_id");
                        });

                    b.OwnsMany("RouteGuard.Platform.TripExecutionMonitoring.Domain.Model.Entities.Incident", "Incidents", b1 =>
                        {
                            b1.Property<Guid>("Id")
                                .HasColumnType("char(36)")
                                .HasColumnName("id");

                            b1.Property<string>("Description")
                                .IsRequired()
                                .HasMaxLength(500)
                                .HasColumnType("varchar(500)")
                                .HasColumnName("description");

                            b1.Property<DateTimeOffset>("ReportedAt")
                                .HasColumnType("datetime")
                                .HasColumnName("reported_at");

                            b1.Property<Guid>("TripId")
                                .HasColumnType("char(36)")
                                .HasColumnName("trip_id");

                            b1.HasKey("Id")
                                .HasName("p_k_incidents");

                            b1.HasIndex("TripId")
                                .HasDatabaseName("i_x_incidents_trip_id");

                            b1.ToTable("incidents");

                            b1.WithOwner()
                                .HasForeignKey("TripId")
                                .HasConstraintName("f_k_incidents_trips_trip_id");
                        });

                    b.Navigation("Attendances");

                    b.Navigation("Incidents");
                });
#pragma warning restore 612, 618
        }
    }
}
